sudo: false
env:
  - CXX=g++-4.8 npm_registry=https://registry.npmjs.org
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - 'npm run ci'
  - 'sh test/git-clone-install.sh'
  - 'node test/all.js'
after_script:
  - 'npm i codecov && codecov'
